import { unstable_cache } from 'next/cache';
import { NextResponse } from 'next/server';

import {
  DEFAULT_FORECAST_MODEL,
  DEFAULT_FORECAST_SERVICE,
  DEFAULT_FORECAST_TARGETS,
  FORECAST_TTL_SECONDS,
} from '@/consts/projections';
import type { ProjectionData, ProjectionsResponse } from '@/data/types';
import { getLatestForecasts } from '@/lib/db/analytics';
import { buildProjection, COIN_CONFIGS } from '@/lib/forecast/mock';
import { validateForecastParams } from '@/lib/forecast/params';
import { runForecast } from '@/lib/forecast/run';

/** Picks the most-recently-generated row of a stored batch to represent the
 * batch's `generatedAt`/`service`/`model` at the response's top level. Rows
 * in a batch are not guaranteed to share one timestamp (`getLatestForecasts`
 * picks each symbol's own latest independently) or one provider (each symbol
 * could, historically, have been generated by a different service/model
 * pair) — ISO-8601 strings sort correctly lexically, so a plain string
 * comparison finds the newest without parsing to `Date`. */
function mostRecent(projections: readonly ProjectionData[]): ProjectionData {
  return projections.reduce((latest, current) =>
    current.generatedAt > latest.generatedAt ? current : latest,
  );
}

function getCachedForecast(service: string, model: string) {
  return unstable_cache(
    async (): Promise<ProjectionsResponse> => {
      // Cache-of-record lookup order (spec 019 Slice 2): a stored, fresh,
      // full-coverage batch is served with zero model calls. Partial
      // coverage of the target batch is treated as a miss for the whole
      // batch by `getLatestForecasts` itself (see its doc comment and
      // decisions.md §3) — mixing a fresh curve for one symbol with a stale
      // one for another would present as one coherent forecast when it
      // isn't. A DB read failure is likewise folded into an empty array by
      // `getLatestForecasts` (logged there, not here), so it is
      // indistinguishable from a genuine cache miss at this call site —
      // both correctly fall through to `runForecast` below.
      const symbols = DEFAULT_FORECAST_TARGETS.map((target) => target.symbol);
      const stored = await getLatestForecasts(symbols, FORECAST_TTL_SECONDS * 1000);

      if (stored.length > 0) {
        const newest = mostRecent(stored);
        return {
          projections: stored,
          generatedAt: newest.generatedAt,
          service: newest.service,
          model: newest.model,
        };
      }

      const result = await runForecast({
        targets: DEFAULT_FORECAST_TARGETS,
        service,
        model,
        awaitPersist: false,
      });

      return {
        projections: result.projections,
        generatedAt: result.generatedAt,
        service: result.service,
        model: result.model,
      };
    },
    ['projections', service, model],
    { revalidate: FORECAST_TTL_SECONDS, tags: ['projections'] },
  );
}

export async function GET(request: Request): Promise<NextResponse> {
  const { searchParams } = new URL(request.url);
  const rawService = searchParams.get('service') ?? DEFAULT_FORECAST_SERVICE;
  const rawModel = searchParams.get('model') ?? DEFAULT_FORECAST_MODEL;
  // Validate before the cache key is derived (spec 019 AC 2.2): an invalid pair
  // must collapse onto the same cache entry — and the same model call — as the
  // default pair, never key the cache on raw, unvalidated query values.
  const { service, model } = validateForecastParams(rawService, rawModel);

  // When mock data is enabled, return seeded mock data immediately
  if (process.env.NEXT_PUBLIC_USE_MOCK_DATA === 'true') {
    const projections: ProjectionData[] = COIN_CONFIGS.map(buildProjection);
    return NextResponse.json({
      projections,
      generatedAt: new Date().toISOString(),
      service,
      model,
    });
  }

  try {
    const cached = getCachedForecast(service, model);
    const response = await cached();
    return NextResponse.json(response);
  } catch {
    return NextResponse.json({ error: 'Forecast generation failed' }, { status: 502 });
  }
}
